spring.application.name=task-manager

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/taskdb}
spring.datasource.username=${DB_USERNAME:taskuser}
spring.datasource.password=${DB_PASSWORD:taskpass}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

server.port=${PORT:8080}

# Origines autorisées à appeler l'API (séparées par des virgules)
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}